name: Forecast on Quarterly Cup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *" # runs at midnight every 2 days

# Add concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false


# Daily job to run the simple forecast bot
jobs:
  daily_build:
    runs-on: ubuntu-latest # determines the machine that will run the job - keep as is
    environment: Quarterly_Cup
    steps: # sets up the steps that will be run in order
      # setup repository with all necessary dependencies - keep as is
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run bot
        run: |
          poetry run python main_customise.py --mode quarterly_cup
        # this reads the environment variables from the github repository.
        # Store under Settings --> Secrets and variables --> Actions
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          NIM_BASE_URL: ${{ secrets.NIM_BASE_URL }}
          NIM_API_KEY: ${{ secrets.NIM_API_KEY }}
          DEFAULT_AI_MODEL: ${{ secrets.DEFAULT_AI_MODEL }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}